---
abstract: 'Dancer logger engine for Sys::Syslog'
author:
  - 'Alexis Sukrieh <sukria@sukria.net>'
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Dancer: '0'
  Dancer::ModuleLoader: '0'
  Dancer::Test: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Logger-Syslog
provides:
  Dancer::Logger::Syslog:
    file: lib/Dancer/Logger/Syslog.pm
    version: '0.6'
requires:
  Dancer::Config: '0'
  Dancer::Logger::Abstract: '0'
  File::Basename: '0'
  Sys::Syslog: '0'
  base: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dancer-Logger-Syslog
  homepage: http://search.cpan.org/dist/Dancer-Logger-Syslog/
  repository: https://github.com/PerlDancer/Dancer-Logger-Syslog.git
version: '0.6'
x_authority: cpan:SUKRIA
x_contributors:
  - 'Sam Crawley <samc@catalyst.net.nz>'
  - 'Sergey Romanov <complefor@rambler.ru>'
