--- #YAML:1.0
name:               Dancer-Logger-Syslog
version:            0.2
abstract:           Dancer logger engine for Sys::Syslog
author:
    - Alexis Sukrieh <sukria@sukria.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:       1.123
    Sys::Syslog:  0
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
