---
abstract: 'Dancer logger engine for Sys::Syslog'
author:
  - 'Alexis Sukrieh <sukria@sukria.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Logger-Syslog
no_index:
  directory:
    - t
    - inc
requires:
  Dancer: 1.123
  Sys::Syslog: 0
  Test::More: 0
version: 0.3
